<?php

/**
 * Shared runtime signals: WebSocket relay usage, canvas-like nodes, stall bookkeeping (vendor ticks use this).
 */
function ipmiProxyBuildKvmRuntimeProgressHelpersJs(): string
{
    return ''
        . 'var KVM_TMO=45000;try{KVM_TMO=parseInt(String((PLAN&&PLAN.console_ready_timeout_ms)||45000),10)||45000;}catch(_kt){KVM_TMO=45000;}'
        . 'function kvmNow(){try{return Date.now();}catch(e){return 0;}}'
        . 'function kvmTouchProgress(st){try{st.lastProgress=kvmNow();}catch(e){}}'
        . 'function kvmWsRelaySeen(){try{var e=performance.getEntriesByType("resource"),i;for(i=0;i<e.length;i++){var n=String(e[i].name||"");if(n.indexOf("ipmi_ws_relay.php")>=0||n.indexOf("/wss/")>=0||n.indexOf("/ws/")>=0)return true;}}catch(e0){}'
        . 'try{if(window.__ipmi_kvm_ws_relay_ts&&(kvmNow()-window.__ipmi_kvm_ws_relay_ts)<180000)return true;}catch(e1){}return false;}'
        . 'function kvmVisibleCanvasLike(doc){try{'
        . 'if(!doc||!doc.querySelectorAll)return false;'
        . 'var C=doc.querySelectorAll("canvas");for(var i=0;i<C.length&&i<24;i++){var c=C[i];if(c&&c.width>80&&c.height>60)return true;}'
        . 'var V=doc.querySelectorAll("video");if(V&&V.length)return true;'
        . '}catch(e){}return false;}'
        . 'function kvmAnyFrameCanvas(ctx){try{'
        . 'var L=collectContexts();for(var i=0;i<L.length;i++){try{var d=L[i].document;if(d&&kvmVisibleCanvasLike(d))return true;}catch(e2){}}'
        . '}catch(e3){}return false;}'
        . 'function kvmIloRendererDetected(ctx){try{return !!(consoleVisible(ctx)||(ctx&&ctx.renderer&&ctx.renderer.connected));}catch(e){return false;}}'
        . 'function kvmIloWsTransportEvidence(){return kvmWsRelaySeen();}'
        . 'function kvmIloTransportDetected(){return kvmIloWsTransportEvidence();}'
        . 'function kvmIloRendererOrContainerPresent(ctx){try{'
        . 'if(kvmIloRendererDetected(ctx))return true;'
        . 'var L=collectContexts();for(var i=0;i<L.length;i++){try{'
        . 'if(rcWindowVisible(L[i]))return true;'
        . 'if(L[i].document&&L[i].document.getElementById&&L[i].document.getElementById("ircWindow"))return true;'
        . '}catch(e0){}}'
        . '}catch(e){}return false;}'
        . 'function kvmIloLoadingPleaseWaitAny(){try{'
        . 'var L=collectContexts();'
        . 'for(var i=0;i<L.length;i++){try{'
        . 'var d=L[i].document;if(!d||!d.body)continue;'
        . 'var t=String((d.body.innerText||d.body.textContent||"")).toLowerCase();'
        . 'if(t.indexOf("please wait")>=0&&t.indexOf("loading")>=0)return true;'
        . 'if(t.indexOf("loading, please wait")>=0)return true;'
        . 'if(t.indexOf("loading")>=0&&t.indexOf("wait")>=0&&t.length<4200)return true;'
        . '}catch(e1){}}'
        . '}catch(e){}return false;}'
        . 'function kvmIloRcWindowAny(){try{var L=collectContexts();for(var i=0;i<L.length;i++){try{if(rcWindowVisible(L[i]))return true;}catch(e2){}}}catch(e){}return false;}'
        . 'function ipmiProxyIloPathIsManagementShellish(){try{var pl=pathLower();if(pl.indexOf("/html/application.html")>=0)return false;if(pl.indexOf("/html/rc_info")>=0||pl.indexOf("/html/irc")>=0)return false;if(pl.indexOf("/index.html")>=0||pl==="/"||pl===""||pl.indexOf("/restgui/")>=0)return true;}catch(e){}return false;}'
        . 'function ipmiProxyIloConsoleRouteReached(){try{var pl=pathLower();return pl.indexOf("/html/application.html")>=0||pl.indexOf("/html/rc_info")>=0||pl.indexOf("/html/irc")>=0;}catch(e){return false;}}'
        . 'function ipmiProxyIloApplicationPathLoaded(){try{return pathLower().indexOf("/html/application.html")>=0;}catch(e){return false;}}'
        . 'function ipmiProxyIloCanvasLooksActive(doc){try{'
        . 'if(!doc||!doc.querySelectorAll)return false;'
        . 'var C=doc.querySelectorAll("canvas");for(var i=0;i<C.length&&i<32;i++){var c=C[i];if(!c||c.width<80||c.height<60)continue;try{var st=window.getComputedStyle?window.getComputedStyle(c):null;if(st&&st.display==="none")continue;var r=c.getBoundingClientRect();if(r.width>=48&&r.height>=36)return true;}catch(_ce){}}'
        . 'var V=doc.querySelectorAll("video");for(var j=0;j<V.length&&j<8;j++){var v=V[j];if(!v)continue;try{var r2=v.getBoundingClientRect();if(r2.width>=64&&r2.height>=48)return true;}catch(_ve){}}'
        . '}catch(e){}return false;}'
        . 'function ipmiProxyIloConsoleContentFrameVisible(doc){try{if(!doc||!doc.querySelectorAll)return false;var F=doc.querySelectorAll("iframe,frame");for(var fi=0;fi<F.length&&fi<40;fi++){var el=F[fi],src=String(el.getAttribute("src")||"").toLowerCase();if(src.indexOf("jnlp")>=0)continue;if(src.indexOf("irc")>=0||src.indexOf("rc_info")>=0){var r=el.getBoundingClientRect();if(r.width>48&&r.height>48)return true;}}}catch(e){}return false;}'
        . 'function ipmiProxyIloHasLiveDisplayEvidence(ctx){try{'
        . 'var L=collectContexts();for(var x=0;x<L.length;x++){try{var d=L[x].document;if(d&&(ipmiProxyIloCanvasLooksActive(d)||ipmiProxyIloConsoleContentFrameVisible(d)))return true;}catch(e1){}}'
        . 'for(var y=0;y<L.length;y++){try{if(rcWindowVisible(L[y]))return true;}catch(e2){}}'
        . '}catch(e){}'
        . 'try{if(ipmiProxyIloCanvasLooksActive(document)||ipmiProxyIloConsoleContentFrameVisible(document))return true;}catch(e3){}'
        . 'return false;}'
        . 'function ipmiProxyIloLooksLikeLiveConsoleSurface(ctx){return ipmiProxyIloHasLiveDisplayEvidence(ctx);}'
        . 'function ipmiProxyIloConsoleViewportLooksReal(ctx){return ipmiProxyIloHasLiveDisplayEvidence(ctx);}'
        . 'function ipmiProxyIloHasVisibleLiveConsole(ctx){return ipmiProxyIloHasLiveDisplayEvidence(ctx);}'
        . 'function ipmiProxyIloLoadingOnlyStatePresent(){return kvmIloLoadingPleaseWaitAny();}'
        . 'function ipmiProxyIloLooksLikeOverviewShell(doc){try{'
        . 'if(!doc||!doc.body)return false;'
        . 'var t=String(doc.title||"").toLowerCase();'
        . 'if((t.indexOf("overview")>=0&&(t.indexOf("ilo")>=0||t.indexOf("hpe")>=0))||(t.indexOf("ilo")>=0&&t.indexOf("overview")>=0))return true;'
        . 'var b=String(doc.body.innerText||doc.body.textContent||"").toLowerCase();'
        . 'if(b.indexOf("ilo overview")>=0)return true;'
        . 'if(b.indexOf("remote console")>=0&&b.indexOf("integrated")>=0&&ipmiProxyIloCanvasLooksActive(doc))return false;'
        . 'if(b.indexOf("system information")>=0&&b.indexOf("firmware")>=0&&b.indexOf("serial number")>=0&&!ipmiProxyIloCanvasLooksActive(doc))return true;'
        . 'var nav=doc.querySelectorAll("[class*=nav],[class*=menu],.tree_view,#tabber");'
        . 'if(nav.length>=2&&b.indexOf("overview")>=0&&!ipmiProxyIloCanvasLooksActive(doc)&&!doc.getElementById("ircWindow"))return true;'
        . 'return false;}catch(e){return false;}}'
        . 'function ipmiProxyIloApplicationLoadedButConsoleNotReached(ctx){try{if(!ipmiProxyIloApplicationPathLoaded())return false;if(ipmiProxyIloHasLiveDisplayEvidence(ctx)||kvmIloRcWindowAny())return false;return true;}catch(e){return false;}}'
        . 'function ipmiProxyIloApplicationLoadedShellOnly(ctx){try{if(!ipmiProxyIloApplicationPathLoaded())return false;if(ipmiProxyIloHasLiveDisplayEvidence(ctx)||kvmIloRcWindowAny())return false;var doc=(ctx&&ctx.document)?ctx.document:document;if(!doc||!doc.body)return true;if(ipmiProxyIloLooksLikeOverviewShell(doc))return true;var b=String(doc.body.innerText||doc.body.textContent||"").toLowerCase();if(b.indexOf("ilo overview")>=0)return true;if(!ipmiProxyIloCanvasLooksActive(doc)&&!doc.getElementById("ircWindow")){if(b.indexOf("overview")>=0&&(b.indexOf("firmware")>=0||b.indexOf("serial")>=0||b.indexOf("health")>=0))return true;var T=doc.querySelectorAll("table");if(T&&T.length>=4&&(b.indexOf("power")>=0||b.indexOf("temperature")>=0))return true;}return false;}catch(e){return false;}}'
        . 'function ipmiProxyIloHelperActivitySupportsButDoesNotConfirm(ctx){try{return ipmiProxyIloHelperActivityPresent()&&!ipmiProxyIloHasLiveDisplayEvidence(ctx)&&!kvmIloRcWindowAny()&&(ipmiProxyIloApplicationLoadedShellOnly(ctx)||ipmiProxyIloLooksLikeOverviewShell((ctx&&ctx.document)?ctx.document:document));}catch(e){return false;}}'
        . 'function ipmiProxyIloShellVsConsoleStateStore(o){try{window.__ipmi_ilo_shell_vs_console=o||{};}catch(e){}}'
        . 'function ipmiProxyIloShellVsConsoleStateLoad(){try{return window.__ipmi_ilo_shell_vs_console||null;}catch(e){return null;}}'
        . 'function ipmiProxyIloShellVsConsoleVerdict(){try{var o=ipmiProxyIloShellVsConsoleStateLoad();return o&&o.final_verdict?String(o.final_verdict):"";}catch(e){return"";}}'
        . 'function ipmiProxyIloManagementShellStillVisible(ctx){try{'
        . 'if(ipmiProxyIloHasLiveDisplayEvidence(ctx))return false;'
        . 'if(kvmIloRcWindowAny())return false;'
        . 'if(kvmIloLoadingPleaseWaitAny())return false;'
        . 'if(typeof hasIloRendererHost==="function"&&ctx&&hasIloRendererHost(ctx))return false;'
        . 'var doc=null;try{doc=(ctx&&ctx.document)?ctx.document:document;}catch(_d0){doc=document;}'
        . 'if(!doc)return false;'
        . 'if(ipmiProxyIloLooksLikeOverviewShell(doc))return true;'
        . 'if(ipmiProxyIloApplicationLoadedShellOnly(ctx))return true;'
        . 'if(ipmiProxyIloPathIsManagementShellish()&&!ipmiProxyIloConsoleRouteReached())return true;'
        . 'return false;}catch(e){return false;}}'
        . 'function ipmiProxyIloLiveConsoleNotYetReached(ctx){try{return !ipmiProxyIloHasLiveDisplayEvidence(ctx)&&!kvmIloRcWindowAny();}catch(e){return true;}}'
        . 'function ipmiProxyIloHelperActivityPresent(){try{var e=performance.getEntriesByType("resource"),i,u;for(i=0;i<e.length;i++){u=String(e[i].name||"").toLowerCase();if(u.indexOf("jnlp_template")>=0||u.indexOf("jnlp")>=0&&u.indexOf(".html")>=0)return true;if(u.indexOf("/html/irc")>=0||u.indexOf("irc.html")>=0)return true;if(u.indexOf("rc_info")>=0)return true;}}catch(e0){}return false;}'
        . 'function ipmiProxyIloHelperActivityCorrelatesWithConsoleReach(ctx){try{return ipmiProxyIloHelperActivityPresent()&&ipmiProxyIloHasLiveDisplayEvidence(ctx)&&!ipmiProxyIloApplicationLoadedShellOnly(ctx);}catch(e){return false;}}'
        . 'function ipmiProxyIloHelperActivityWithoutConsoleTransition(ctx){return ipmiProxyIloHelperActivityPresent()&&ipmiProxyIloManagementShellStillVisible(ctx);}'
        . 'function ipmiProxyIloHelperSupportsVisibleTransition(ctx){try{return ipmiProxyIloHelperActivityCorrelatesWithConsoleReach(ctx);}catch(e){return false;}}'
        . 'function ipmiProxyIloHelperSeenWithoutVisibleProgress(ctx){try{return ipmiProxyIloHelperActivityPresent()&&!ipmiProxyIloHasLiveDisplayEvidence(ctx)&&!kvmIloRcWindowAny();}catch(e){return false;}}'
        . 'function ipmiProxyIloDomSnapshotSig(w){try{var d=(w&&w.document)?w.document:document;if(!d||!d.body)return"e";var t=String(d.body.innerText||d.body.textContent||"").replace(/\\s+/g," ").trim();var la=0,lif=0;try{la=d.querySelectorAll("a[href]").length;}catch(_a){}try{lif=d.querySelectorAll("iframe,frame").length;}catch(_f){}return String(t.length)+":"+String(la)+":"+String(lif);}catch(e){return"e";}}'
        . 'function ipmiProxyIloLooksLikeShellOnlyUi(ctx){return ipmiProxyIloManagementShellStillVisible(ctx);}'
        . 'function ipmiProxyIloLooksLikeWhiteScreenStall(tick,st){try{var d=document;if(!d||!d.body)return false;var t=String(d.body.innerText||d.body.textContent||"").replace(/\\s+/g," ").trim();var L=t.length;var ch=d.body.children?d.body.children.length:0;var ifc=0;try{var F=d.querySelectorAll("iframe,frame");if(F)ifc=F.length;}catch(_e){}var bg="";try{bg=String(d.body.style&&d.body.style.backgroundColor||"").toLowerCase();}catch(_b){}if(L<32&&ch<=3&&ifc<=1)return true;if(L<95&&ifc<=1&&ch<=2&&!ipmiProxyIloHasLiveDisplayEvidence(window)&&tick>16)return true;if(st&&st.discNavTriggered&&(L<40||bg==="rgb(255, 255, 255)"||bg==="#ffffff")&&tick>20&&!ipmiProxyIloHasLiveDisplayEvidence(window))return true;return false;}catch(e){return false;}}'
        . 'function ipmiProxyIloLaunchDiscoveryStateStore(o){try{window.__ipmi_ilo_launch_discovery=o||{};}catch(e){}}'
        . 'function ipmiProxyIloLaunchDiscoveryStateLoadBr(){try{return window.__ipmi_ilo_launch_discovery||null;}catch(e){return null;}}'
        . 'function ipmiProxyIloRegisterLaunchHelperSignal(st){try{if(!st)return;var h=ipmiProxyIloHelperActivityPresent();if(!h||st.helperReg)return;st.helperReg=true;if(st.launchSurfaceFound||st.discTriggered||st.discNavTriggered){st.helperAidedDiscovery=true;try{_kvmDbg("ilo_launch_helper_aided_discovery",{});}catch(_h1){}}else{try{_kvmDbg("ilo_launch_helper_seen",{phase:"discovery"});}catch(_h2){}}}catch(e){}}'
        . 'function ipmiProxyIloHelperAidedDiscovery(st){return !!(st&&st.helperAidedDiscovery);}'
        . 'function ipmiProxyIloArmLaunchOutcomeProbe(st,n,sig,ws,live){try{if(!st)return;st.pendingOutcomeCheck=n+5;st.launchSigBefore=sig||"";st.__wsBefore=!!ws;st.__liveBefore=!!live;try{st.__wideSnapBefore=JSON.stringify(typeof ipmiProxyIloCapturePreLaunchSnapshot==="function"?ipmiProxyIloCapturePreLaunchSnapshot():{});}catch(_w1){st.__wideSnapBefore="";}}catch(e){}}'
        . 'function ipmiProxyIloRecordLaunchAttemptOutcome(st,sigBefore,wsBefore,liveBefore,tick){try{if(!st)return{effective:false,domChanged:false,wsUp:false,liveUp:false,wideMeaningful:false};var sig=ipmiProxyIloDomSnapshotSig(window);var ws=kvmIloWsTransportEvidence();var live=ipmiProxyIloHasLiveDisplayEvidence(window);var domChanged=(sigBefore&&sig&&sig!==sigBefore);var wsUp=(!wsBefore&&ws);var liveUp=(!liveBefore&&live);var wideMeaningful=false;try{var pre=JSON.parse(st.__wideSnapBefore||"{}");var post=(typeof ipmiProxyIloCapturePostLaunchSnapshot==="function")?ipmiProxyIloCapturePostLaunchSnapshot():{};var wdiff=(typeof ipmiProxyIloDiffLaunchSnapshots==="function")?ipmiProxyIloDiffLaunchSnapshots(pre,post):{meaningful:false,changed:[]};wideMeaningful=!!(wdiff&&wdiff.meaningful);try{_kvmDbg("ilo_launch_snapshot_diff",{narrow_sig_change:domChanged?1:0,wide_fields:(wdiff&&wdiff.changed)?wdiff.changed.join(","):"",wide_meaningful:wideMeaningful?1:0});}catch(_wd){}}catch(_we){}var effective=domChanged||wsUp||liveUp||wideMeaningful;if(effective&&wideMeaningful){try{_kvmDbg("ilo_launch_action_changed_shell_state",{via:"wide_snapshot"});}catch(_ss2){}}try{ipmiProxyIloLaunchDiscoveryStateStore({sig_before:sigBefore||"",sig_after:sig,dom_changed:domChanged?1:0,ws_before:wsBefore?1:0,ws_after:ws?1:0,live_before:liveBefore?1:0,live_after:live?1:0,effective:effective?1:0,wide_meaningful:wideMeaningful?1:0,tick:tick||0,ts:Date.now()});}catch(_ss){}if(!effective){try{_kvmDbg("ilo_launch_action_no_effect",{tick:tick,dom_changed:domChanged?1:0,ws:ws?1:0,live:live?1:0,wide:wideMeaningful?1:0});}catch(_ne){}}else{try{_kvmDbg("ilo_launch_function_effective",{tick:tick,source:"deferred_probe"});}catch(_ef){}}return {effective:effective,domChanged:domChanged,wsUp:wsUp,liveUp:liveUp,wideMeaningful:wideMeaningful};}catch(e){return{effective:false,domChanged:false,wsUp:false,liveUp:false,wideMeaningful:false};}}'
        . 'function ipmiProxyIloConsoleReadinessVerdict(p){try{p=p||{};if(p.fin)return"native_console_strongly_confirmed";if(p.launchFailed)return"launch_discovery_failed";if(p.noEffect)return"launch_action_no_effect";if(p.whiteStall)return"launch_discovery_failed";if(p.specShell&&!p.discoveryStarted)return"shell_autolaunch_allowed";if(p.specShell&&p.discoveryStarted&&!p.transport&&!p.live&&p.shellEscalationConsumed&&p.mgmtVisible)return"console_start_failed_no_transport";if(p.specShell&&p.discoveryStarted&&!p.transport&&!p.live&&p.sessReady===false&&p.launchTried)return"console_start_failed_no_session_ready";return p.inProgress||"launch_discovery_in_progress";}catch(e){return"unknown";}}'
        . 'function ipmiProxyIloFinalizeReadinessFromDiscovery(st,verdict,detail){try{if(!st)return;st.finalDiscoveryVerdict=String(verdict||"");try{ipmiProxyIloLaunchDiscoveryStateStore({final_discovery_verdict:st.finalDiscoveryVerdict,detail:String(detail||""),ts:Date.now()});}catch(_fs){}try{_kvmDbg("ilo_console_readiness_verdict",{verdict:st.finalDiscoveryVerdict,detail:String(detail||""),discovery:1});}catch(_fd){}}catch(e){}}'
        . 'function ipmiProxyIloLooksLikeManagementShellOnly(ctx){return ipmiProxyIloManagementShellStillVisible(ctx);}'
        . 'function ipmiProxyIloHasOnlyShellUi(ctx){return ipmiProxyIloManagementShellStillVisible(ctx);}'
        . 'function ipmiProxyIloShouldRejectShellAsConsoleSuccess(ctx,st){return ipmiProxyIloManagementShellStillVisible(ctx)&&!kvmIloWsTransportEvidence();}'
        . 'function ipmiProxyIloShouldRejectShellOnlyAsStrongConfirmation(ctx){var live=ipmiProxyIloHasLiveDisplayEvidence(ctx);if(live)return false;return ipmiProxyIloManagementShellStillVisible(ctx)||(ipmiProxyIloHelperActivityPresent()&&ipmiProxyIloApplicationLoadedShellOnly(ctx));}'
        . 'function ipmiProxyIloCanStronglyConfirmLiveConsole(ctx,st){var probe={finStable:st?st.finStable||0:0};var r=kvmIloReadyToFinalize(ctx,probe);return !!(r&&r.ok);}'
        . 'function ipmiProxyIloFinalizeStrongConfirmationFromVisibleUi(ctx,st,rf){var v=(rf&&rf.ok)?"native_console_strongly_confirmed":(rf&&rf.why?String(rf.why):"console_not_ready");try{ipmiProxyIloShellVsConsoleStateStore({final_verdict:v,finalize:rf||{},live_console_visible:rf&&rf.ok?1:0,native_console_strongly_confirmed:rf&&rf.ok?1:0,ts:Date.now()});}catch(e){}return rf;}'
        . 'function kvmIloSessionReadyEvidence(ctx){'
        . 'try{'
        . 'if(ipmiProxyIloHasLiveDisplayEvidence(ctx))return true;'
        . 'if(kvmIloRcWindowAny()&&!kvmIloLoadingPleaseWaitAny())return true;'
        . '}catch(e){}return false;}'
        . 'function kvmIloInteractiveLikely(ctx){'
        . 'if(kvmIloRendererDetected(ctx))return true;'
        . 'try{if(rcWindowVisible(ctx))return true;}catch(e0){}'
        . 'return kvmAnyFrameCanvas(ctx);'
        . '}'
        . 'function kvmIloReadyToFinalize(ctx,st){'
        . 'var ws=kvmIloWsTransportEvidence();'
        . 'var load=kvmIloLoadingPleaseWaitAny();'
        . 'var live=ipmiProxyIloHasLiveDisplayEvidence(ctx);'
        . 'var mgmt=ipmiProxyIloManagementShellStillVisible(ctx);'
        . 'var ov=false;try{var _d=(ctx&&ctx.document)?ctx.document:document;ov=ipmiProxyIloLooksLikeOverviewShell(_d);}catch(_ov){}'
        . 'var appPl=ipmiProxyIloApplicationPathLoaded();'
        . 'var tk=st?st.__lastTick||0:0;'
        . 'if(load)return {ok:false,why:"loading_only_state",loading_only:1};'
        . 'if(appPl&&!live&&tk>20&&ipmiProxyIloLooksLikeWhiteScreenStall(tk,st)){try{_kvmDbg("ilo_white_screen_failure_finalized",{tick:tk,path:"application"});_kvmDbg("ilo_white_screen_persisted",{tick:tk,path:"application"});_kvmDbg("ilo_application_loaded_white_screen",{tick:tk});}catch(_wsf){}return {ok:false,why:"application_loaded_white_screen",white_screen:1,app_path:1};}'
        . 'if(mgmt&&!live){var why="shell_only_management_ui",app=ipmiProxyIloApplicationPathLoaded();if(app&&ov)why="native_console_route_reached_but_shell_only";else if(app)why="application_loaded_console_not_reached";else if(ov)why="shell_only_management_ui";return {ok:false,why:why,shell_only:1,management_shell_still_visible:1,app_path:app?1:0,overview_shell:ov?1:0,native_route_not_ready:app&&!live?1:0};}'
        . 'if(!ws)return {ok:false,why:"no_relay_transport"};'
        . 'if(!live)return {ok:false,why:"transport_without_live_display"};'
        . 'st.finStable=(st.finStable||0)+1;'
        . 'if(st.finStable>=3)return {ok:true,why:"user_visible_console_success"};'
        . 'return {ok:false,why:"stabilizing"};}'
        . 'function kvmHookWsRelayProbe(){try{'
        . 'if(!window.WebSocket||window.__ipmi_kvm_ws_progress_hook)return;'
        . 'window.__ipmi_kvm_ws_progress_hook=true;var W0=window.WebSocket;'
        . 'window.WebSocket=function(u,p){try{var us=typeof u==="string"?u:"";var low=us.toLowerCase();if(low.indexOf("ipmi_ws_relay")>=0||low.indexOf("/wss/")>=0||low.indexOf("/ws/")>=0){window.__ipmi_kvm_ws_relay_ts=kvmNow();try{_kvmDbg("ipmi_ws_relay_client_open",String(us).substring(0,96));}catch(e1){}}}catch(e2){}'
        . 'return new W0(u,p);};window.WebSocket.prototype=W0.prototype;'
        . '}catch(e3){}}'
        . 'kvmHookWsRelayProbe();'
        . 'function kvmIdracViewerBootstrap(){try{'
        . 'var p=pathLower();if(p.indexOf("viewer")>=0||p.indexOf("console")>=0)return true;'
        . 'var b=String(document.body&&document.body.innerHTML||"").toLowerCase();'
        . 'return b.indexOf("avct")>=0||b.indexOf("vmrc")>=0||b.indexOf("websocket")>=0;'
        . '}catch(e){return false;}}'
        . 'function kvmIdracTransportLikely(){return kvmWsRelaySeen()||kvmIdracViewerBootstrap();}'
        . 'function kvmIdracInteractiveLikely(){try{return kvmVisibleCanvasLike(document)||kvmAnyFrameCanvas(window);}catch(e){return false;}}'
        . 'function kvmSupermicroInteractiveLikely(){try{'
        . 'if(kvmVisibleCanvasLike(document))return true;'
        . 'var b=String(document.body&&document.body.innerHTML||"").toLowerCase();'
        . 'return b.indexOf("ikvm")>=0&&b.indexOf("canvas")>=0;'
        . '}catch(e){return false;}}';
}
