<?php

function ipmiProxyBuildIdracKvmScript(): string
{
    return 'if(FAMILY==="idrac"){'
        . 'var wantDr=(PLAN&&PLAN.kvm_entry_path)?String(PLAN.kvm_entry_path):"/index.html";'
        . 'var bootDr=(PLAN&&PLAN.console_bootstrap_path)?String(PLAN.console_bootstrap_path):"/viewer.html";'
        . 'var _idrN=0,_idrBooted=false,_idrSt={lastProgress:kvmNow(),clicks:0,navs:0,reported:{boot:false,launch:false,trans:false},stall:false};'
        . '_kvmDbg("idrac_shell_detected",pathLower());'
        . 'kvmTouchProgress(_idrSt);'
        . 'try{'
        . 'if(window.sessionStorage&&!sessionStorage.getItem("_ipmi_idrac_autonav")){'
        . 'sessionStorage.setItem("_ipmi_idrac_autonav","1");'
        . 'var cur=String(location.pathname||"").toLowerCase();'
        . 'if(cur.indexOf("/viewer.html")<0&&cur.indexOf("/console.html")<0&&wantDr){'
        . 'if(wantDr.charAt(0)!=="/")wantDr="/"+wantDr;'
        . 'var curFullDr=location.pathname+(location.search||"");'
        . 'if(wantDr!==curFullDr){_kvmDbg("idrac_console_navigation",wantDr);go(wantDr);}'
        . '}'
        . '}'
        . '}catch(_idr0){}'
        . '(function _idrTick(){_idrN++;'
        . 'try{'
        . 'var _b=String(document.body&&document.body.innerText||"").toLowerCase();'
        . 'if(_b.indexOf("virtual")>=0&&_b.indexOf("console")>=0){kvmTouchProgress(_idrSt);if(!_idrSt.reported.boot){_idrSt.reported.boot=true;_kvmDbg("idrac_viewer_bootstrap_detected",1);}}'
        . 'if(kvmIdracViewerBootstrap()){kvmTouchProgress(_idrSt);}'
        . 'if(kvmIdracTransportLikely()&&!_idrSt.reported.trans){_idrSt.reported.trans=true;kvmTouchProgress(_idrSt);_kvmDbg("idrac_transport_detected",1);}'
        . 'if(kvmIdracInteractiveLikely()){_kvmDbg("idrac_console_interactive_likely",1);markDone();return;}'
        . 'var _L=document.querySelectorAll("a[href],button,[role=button],input[type=button]");'
        . 'for(var _i=0;_i<_L.length;_i++){'
        . 'var _e=_L[_i],_h=String(_e.getAttribute("href")||"").toLowerCase(),_x=String(_e.textContent||"").toLowerCase();'
        . 'if(_h.indexOf("viewer")>=0||_h.indexOf("console")>=0||(_x.indexOf("virtual")>=0&&_x.indexOf("console")>=0)||(_x.indexOf("launch")>=0&&_x.indexOf("console")>=0)||(_x.indexOf("kvm")>=0&&_x.indexOf("launch")>=0)){'
        . 'if(!_idrSt.reported.launch){_idrSt.reported.launch=true;_kvmDbg("idrac_launch_control_found",_h||_x);}'
        . 'if(_idrN%4===0&&_idrSt.clicks<6){_idrSt.clicks++;kvmTouchProgress(_idrSt);try{_e.click();}catch(ec){}}'
        . '}'
        . '}'
        . '}catch(_idr1){}'
        . 'if(!_idrBooted&&_idrN>=26&&bootDr&&pathLower().indexOf("viewer")<0&&pathLower().indexOf("console")<0&&_idrN%12===0){_idrBooted=true;_idrSt.navs++;if(_idrSt.navs<=2){_kvmDbg("idrac_console_navigation",bootDr);try{go(bootDr);return;}catch(eb){}}}'
        . 'if(!_idrSt.stall&&(kvmNow()-_idrSt.lastProgress)>KVM_TMO){_idrSt.stall=true;_kvmDbg("idrac_console_stalled",{ticks:_idrN,clicks:_idrSt.clicks,no_transport:!_idrSt.reported.trans});return;}'
        . 'if(_idrN>=120){_kvmDbg("idrac_console_stalled",{ticks:_idrN,reason:"max_ticks"});return;}'
        . 'setTimeout(_idrTick,380);'
        . '})();'
        . 'return;}';

}
