<?php

/**
 * iLO-only DOM / renderer helpers (collectContexts, startHtml5Irc shims).
 */
function ipmiProxyBuildKvmAutoLaunchIloDomHelpersJs(): string
{
    return ''
        . 'function fnSrc(fn){try{return Function.prototype.toString.call(fn);}catch(e){return"";}}'
        . 'function isRendererStartFn(fn){var s=fnSrc(fn);if(!s)return false;return s.indexOf("new Renderer")!==-1||s.indexOf("renderer = new Renderer")!==-1||s.indexOf("htmlIrcWindowMode")!==-1;}'
        . 'function isWrapperStartFn(fn){var s=fnSrc(fn);if(!s)return false;return s.indexOf("iLO.startHtml5Irc")!==-1&&s.indexOf("new Renderer")===-1;}'
        . 'function getIloDirectTopRenderer(ctx){try{var t=(ctx&&ctx.top)?ctx.top:window.top;if(t&&isRendererStartFn(t.startHtml5Irc))return t;}catch(e){}return null;}'
        . 'function hasIloRendererHost(ctx){try{'
        . 'if(!ctx)return false;'
        . 'if(isRendererStartFn(ctx.startHtml5Irc))return true;'
        . 'if(ctx.document&&ctx.document.getElementById&&ctx.document.getElementById("ircWindow"))return true;'
        . '}catch(e){}return false;}'
        . 'function findIloRendererHost(ctx){'
        . 'var out=[];'
        . 'function add(c){if(!c)return;for(var i=0;i<out.length;i++){if(out[i]===c)return;}out.push(c);}'
        . 'try{add(ctx);}catch(e0){}'
        . 'try{if(ctx&&ctx.parent&&ctx.parent!==ctx)add(ctx.parent);}catch(e1){}'
        . 'try{if(ctx&&ctx.parent&&ctx.parent.parent&&ctx.parent.parent!==ctx.parent)add(ctx.parent.parent);}catch(e2){}'
        . 'try{if(ctx&&ctx.top&&ctx.top!==ctx)add(ctx.top);}catch(e3){}'
        . 'try{if(ctx&&ctx.top&&ctx.top.frames&&ctx.top.frames.appFrame)add(ctx.top.frames.appFrame);}catch(e4){}'
        . 'for(var j=0;j<out.length;j++){if(hasIloRendererHost(out[j]))return out[j];}'
        . 'for(var k=0;k<out.length;k++){try{if(out[k]&&out[k].frameDirectory&&out[k].frameContent){return out[k];}}catch(_e5){}}'
        . 'return ctx||null;'
        . '}'
        . 'function bindIloTopPage(ctx){try{'
        . 'if(!ctx)return null;'
        . 'var host=findIloRendererHost(ctx)||ctx;'
        . 'if(ctx.iLOGlobal){ctx.iLOGlobal.topPage=host;}'
        . 'if(host&&host.iLOGlobal){host.iLOGlobal.topPage=host;}'
        . 'if(ctx.iLOGlobal&&ctx.iLOGlobal.topPage){ctx.iLOGlobal.topPage.appFrame=host;}'
        . 'if(host&&host.iLOGlobal&&host.iLOGlobal.topPage){host.iLOGlobal.topPage.appFrame=host;}'
        . 'return host;'
        . '}catch(e){return ctx||null;}}'
        . 'function ensureIloStartPatched(ctx){try{'
        . 'if(!ctx||!ctx.iLO||typeof ctx.iLO.startHtml5Irc!=="function"||ctx.iLO.__ipmi_start_patched){return;}'
        . 'ctx.iLO.__ipmi_start_orig=ctx.iLO.startHtml5Irc;'
        . 'ctx.iLO.startHtml5Irc=function(){try{'
        . 'try{if(ctx.iLO&&typeof ctx.iLO.setCookie==="function"){ctx.iLO.setCookie("irc",["last","html5"]);}}catch(_c0){}'
        . 'var directTop=getIloDirectTopRenderer(ctx);'
        . 'if(directTop){forceSameTabOpen(directTop);ensureIloFrameResizeShim(directTop);clearIloStaleRenderer(directTop);try{directTop.startHtml5Irc({mode:"WINDOW"});return;}catch(_dt1){}try{directTop.startHtml5Irc();return;}catch(_dt2){}}'
        . 'var host=bindIloTopPage(ctx)||findIloRendererHost(ctx)||ctx;'
        . 'ensureIloFrameResizeShim(host);clearIloStaleRenderer(host);clearIloStaleRenderer(ctx);'
        . 'if(host){forceSameTabOpen(host);'
        . 'if(isRendererStartFn(host.startHtml5Irc)){try{host.startHtml5Irc({mode:"WINDOW"});return;}catch(_e1){}try{host.startHtml5Irc();return;}catch(_e2){}}'
        . '}'
        . 'var orig=ctx.iLO.__ipmi_start_orig;'
        . 'if(orig&&orig!==ctx.iLO.startHtml5Irc){try{return orig.apply(ctx.iLO,arguments);}catch(_e3){}}'
        . '}catch(_e0){}'
        . '};'
        . 'ctx.iLO.__ipmi_start_patched=true;'
        . '}catch(e){}}'
        . 'function isShown(node){try{return !!(node&&node.offsetParent!==null);}catch(e){return false;}}'
        . 'function hasIloShellHost(ctx){try{return !!(ctx&&ctx.document&&ctx.document.getElementById&&ctx.document.getElementById("frameContent"));}catch(e){return false;}}'
        . 'function getIloShellHost(ctx){var out=[];function add(c){if(!c)return;for(var i=0;i<out.length;i++){if(out[i]===c)return;}out.push(c);}try{add(ctx);}catch(e0){}try{if(ctx&&ctx.parent&&ctx.parent!==ctx)add(ctx.parent);}catch(e1){}try{if(ctx&&ctx.parent&&ctx.parent.parent&&ctx.parent.parent!==ctx.parent)add(ctx.parent.parent);}catch(e2){}try{if(ctx&&ctx.top&&ctx.top!==ctx)add(ctx.top);}catch(e3){}for(var j=0;j<out.length;j++){if(hasIloShellHost(out[j]))return out[j];}return null;}'
        . 'function getIloFrameContent(ctx){try{var sh=getIloShellHost(ctx)||ctx;if(sh&&sh.frames&&sh.frames.frameContent)return sh.frames.frameContent;}catch(e){}return null;}'
        . 'function getIloIframeContent(ctx){try{var fc=getIloFrameContent(ctx);if(fc&&fc.frames&&fc.frames.iframeContent)return fc.frames.iframeContent;}catch(e){}return null;}'
        . 'function getIloIframeContentEl(ctx){try{var fc=getIloFrameContent(ctx);if(fc&&fc.document&&fc.document.getElementById){return fc.document.getElementById("iframeContent");}}catch(e){}return null;}'
        . 'function ensureIloIndexAppLoaded(ctx){try{'
        . 'if(!ctx||!ctx.document||!ctx.document.getElementById)return false;'
        . 'var app=ctx.document.getElementById("appFrame");'
        . 'if(!app)return false;'
        . 'var src=String(app.getAttribute("src")||"").toLowerCase();'
        . 'if(src.indexOf("html/application.html")!==-1)return false;'
        . 'if(typeof ctx.showApplication==="function"){ctx.showApplication();return true;}'
        . 'if(src===""||src==="about:blank"){app.setAttribute("src","html/application.html");return true;}'
        . 'return false;'
        . '}catch(e){return false;}}'
        . 'function ensureIloFrameResizeShim(ctx){try{var host=getIloShellHost(ctx)||findIloRendererHost(ctx)||ctx;if(!host||!host.document||!host.document.getElementById)return;var fd=host.document.getElementById("frameDirectory");if(fd&&fd.contentWindow&&typeof fd.contentWindow.frameResize!=="function"){fd.contentWindow.frameResize=function(){};}}catch(e){}}'
        . 'function hasIloRcPage(ctx){try{var ic=getIloIframeContent(ctx);var p=String((ic&&ic.location&&ic.location.pathname)||"").toLowerCase();var ok=(p.indexOf("/html/rc_info.html")!==-1);if(ok){try{var shell=getIloShellHost(ctx)||findIloRendererHost(ctx)||ctx;if(shell){shell.__ipmi_rc_info_loading_ts=0;}}catch(_e0){}}return ok;}catch(e){return false;}}'
        . 'function ensureIloShellLoaded(ctx){try{'
        . 'var host=getIloShellHost(ctx);'
        . 'if(!host||ctx!==host||!host.document)return false;'
        . 'try{if(host.iLOGlobal){host.iLOGlobal.initialLink="rc_info.html";host.iLOGlobal.content="rc_info.html";host.iLOGlobal.initialTab=0;}}catch(_e0){}'
        . 'var frameEl=host.document.getElementById("frameContent");'
        . 'if(!frameEl)return false;'
        . 'var src=String(frameEl.getAttribute("src")||"").toLowerCase();'
        . 'if(src===""||src==="about:blank"){frameEl.setAttribute("src","content.html");return true;}'
        . 'return false;'
        . '}catch(e){return false;}}'
        . 'function rcWindowVisible(ctx){try{'
        . 'if(!ctx||!ctx.document)return false;'
        . 'var w=ctx.document.getElementById("ircWindow");'
        . 'if(!w)return false;'
        . 'try{if(typeof ctx.jQuery==="function"&&ctx.jQuery("#ircWindow").dialog("instance"))return true;}catch(_e0){}'
        . 'return !!(w.offsetParent!==null||String((w.style&&w.style.display)||"").toLowerCase()!=="none");'
        . '}catch(e){return false;}}'
        . 'function clearIloStaleRenderer(ctx){try{'
        . 'var host=findIloRendererHost(ctx)||ctx;if(!host)return false;'
        . 'var target=host,stale=false;'
        . 'try{stale=!!(host.renderer&&host.renderer.connected&&!rcWindowVisible(host));}catch(_e0){}'
        . 'if(!stale&&ctx&&ctx!==host){try{if(ctx.renderer&&ctx.renderer.connected&&!rcWindowVisible(ctx)){target=ctx;stale=true;}}catch(_e1){}}'
        . 'if(!stale||!target)return false;'
        . 'try{if(target.renderer&&target.renderer.worker&&typeof target.renderer.worker.close==="function"){target.renderer.worker.close();}}catch(_e2){}'
        . 'try{if(target.renderer&&target.renderer.decoder&&typeof target.renderer.decoder.terminate==="function"){target.renderer.decoder.terminate();}}catch(_e3){}'
        . 'try{if(target.renderer&&typeof target.renderer.close==="function"){target.renderer.close();}}catch(_e4){}'
        . 'try{if(target.renderer){target.renderer.connected=false;}}catch(_e5){}'
        . 'try{target.renderer=null;}catch(_e6){}'
        . 'try{var w=target.document&&target.document.getElementById?target.document.getElementById("ircWindow"):null;if(w){w.style.display="none";}}catch(_e7){}'
        . 'return true;'
        . '}catch(e){return false;}}'
        . 'function rendererConnected(ctx){try{return !!(ctx&&ctx.renderer&&ctx.renderer.connected);}catch(e){return false;}}'
        . 'function consoleVisible(ctx){try{'
        . 'if(!ctx)return false;'
        . 'if(rendererConnected(ctx))return true;'
        . 'var host=findIloRendererHost(ctx)||ctx;'
        . 'if(host&&host!==ctx&&rendererConnected(host))return true;'
        . '}catch(e){}return false;}'
        . 'function findIloHtml5Button(ctx){try{'
        . 'if(!ctx||!ctx.document)return null;'
        . 'return ctx.document.getElementById("HRCButton")||ctx.document.querySelector("button[data-localize=\'rc_info.html5Console\']")||null;'
        . '}catch(e){return null;}}'
        . 'function iloKvText(s){s=String(s||"").toLowerCase();return(s.indexOf("html5")>=0&&(s.indexOf("console")>=0||s.indexOf("remote")>=0||s.indexOf("irc")>=0))||(s.indexOf("integrated")>=0&&s.indexOf("remote")>=0)||(s.indexOf("launch")>=0&&s.indexOf("console")>=0);}'
        . 'function iloConsoleKeyword(s){s=String(s||"").toLowerCase();if(iloKvText(s))return true;if(s.indexOf("remote console")>=0)return true;if(s.indexOf("integrated remote console")>=0)return true;if(s.indexOf("launch console")>=0)return true;if(s.indexOf("html5 console")>=0)return true;if(s.indexOf("virtual console")>=0)return true;if(s.indexOf("kvm")>=0&&(s.indexOf("console")>=0||s.indexOf("launch")>=0||s.indexOf("remote")>=0))return true;if(s.indexOf("irc")>=0&&s.indexOf("console")>=0)return true;if(s==="console"||s.indexOf(" console")>=0)return true;return false;}'
        . 'function ipmiProxyIloFrameCandidateScore(el){try{var s=0,src=String(el.getAttribute("src")||"").toLowerCase(),nm=String(el.getAttribute("name")||"").toLowerCase(),id=String(el.getAttribute("id")||"").toLowerCase(),cl=String(el.getAttribute("class")||"").toLowerCase(),ti=String(el.getAttribute("title")||"").toLowerCase();if(src.indexOf("rc_info")>=0||src.indexOf("irc.html")>=0)s+=62;if(src.indexOf("application.html")>=0)s+=55;if(src.indexOf("jnlp")>=0||src.indexOf("jnlp_template")>=0)s+=38;if(src.indexOf("html/irc")>=0)s+=45;if(nm.indexOf("appframe")>=0||id.indexOf("appframe")>=0||id==="appframe")s+=28;if(cl.indexOf("console")>=0||ti.indexOf("console")>=0)s+=18;if(nm.indexOf("frame")>=0&&src.indexOf("html/")>=0)s+=12;if(id==="framecontent"||nm==="framecontent"||id==="framedirectory")s+=8;if(src.indexOf("content.html")>=0||src.indexOf("masthead")>=0)s+=6;return s;}catch(e){return 0;}}'
        . 'function ipmiProxyIloFrameCandidateClassify(el,sc){try{var src=String(el.getAttribute("src")||"").toLowerCase(),id=String(el.getAttribute("id")||"").toLowerCase(),nm=String(el.getAttribute("name")||"").toLowerCase();if(id==="framecontent"||nm==="framecontent"||src.indexOf("content.html")>=0)return"shell_frame";if(sc>=40||(src.indexOf("rc_info")>=0||src.indexOf("application.html")>=0||src.indexOf("irc")>=0))return"console_frame_candidate";if(sc>=22||src.indexOf("html/")>=0)return"launcher_frame";return"unrelated";}catch(e){return"unrelated";}}'
        . 'function ipmiProxyIloFindConsoleFrameCandidate(doc){try{if(!doc||!doc.querySelectorAll)return null;var F=doc.querySelectorAll("iframe,frame");var best=null,bs=0;for(var i=0;i<F.length&&i<48;i++){var sc=ipmiProxyIloFrameCandidateScore(F[i]);if(sc>bs){bs=sc;best=F[i];}}if(bs>=22)return {el:best,score:bs,kind:ipmiProxyIloFrameCandidateClassify(best,bs)};}catch(e2){}return null;}'
        . 'function ipmiProxyIloFindNavigableFrame(doc){try{if(!doc||!doc.querySelectorAll)return null;var F=doc.querySelectorAll("iframe,frame");var best=null,bs=0;for(var j=0;j<F.length&&j<48;j++){var sc2=ipmiProxyIloFrameCandidateScore(F[j]);if(sc2>bs){bs=sc2;best=F[j];}}if(bs>=14&&best)return {el:best,score:bs,kind:ipmiProxyIloFrameCandidateClassify(best,bs)};}catch(e3){}return null;}'
        . 'function ipmiProxyIloFindConsoleModuleInApplication(doc){try{if(!doc||!doc.querySelectorAll)return null;var L=doc.querySelectorAll("a[href],button,[role=button],[role=tab],[role=menuitem],.hp-menu-item,.gwt-MenuItem,.nav-item,.tree_view a,li.gwt-MenuItem,[class*=console],[id*=console],[class*=remote],[id*=irc]");for(var i=0;i<L.length&&i<220;i++){var e=L[i],tx=String(e.textContent||e.innerText||"");if(iloConsoleKeyword(tx))return e;var h=String(e.getAttribute("href")||"").toLowerCase();if(h.indexOf("rc_info")>=0||h.indexOf("irc")>=0||h.indexOf("html5")>=0)return e;}return null;}catch(e){return null;}}'
        . 'function ipmiProxyIloFindConsoleLaunchActionInApplication(doc){try{var d0=ipmiProxyIloFindConsoleModuleInApplication(doc);if(d0)return d0;var d1=findIloDeepLaunch({document:doc});if(d1)return d1;var d2=findIloHeuristicLaunch({document:doc});if(d2)return d2;return findIloBestConsoleHrefClickable(doc);}catch(e2){return null;}}'
        . 'function ipmiProxyIloFollowConsoleFrameTransition(doc,st){try{if(!doc||!st||st.reported.consoleFrameFollowed)return false;var fc=ipmiProxyIloFindConsoleFrameCandidate(doc);if(!fc||!fc.el)return false;var src=String(fc.el.getAttribute("src")||"").toLowerCase();var shellish=(fc.kind==="shell_frame")||(src.indexOf("content.html")>=0||src.indexOf("masthead")>=0||src===""||src==="about:blank");if(fc.score>=16&&shellish&&src.indexOf("rc_info")<0&&src.indexOf("irc")<0){try{fc.el.setAttribute("src","html/rc_info.html");st.reported.consoleFrameFollowed=true;_kvmDbg("ilo_console_content_frame_followed",{score:fc.score,kind:fc.kind||""});return true;}catch(_ff){}}return false;}catch(e){return false;}}'
        . 'function ipmiProxyIloCaptureLaunchSnapshotDoc(d){try{var out={path:"",hash:"",title:"",iframeN:0,iframeSrcSig:"",bodyLen:0,aLen:0};if(!d||!d.documentElement)return out;try{out.path=String(location.pathname||"").toLowerCase();out.hash=String(location.hash||"").toLowerCase();}catch(_p){}try{out.title=String(d.title||"").substring(0,120);}catch(_t){}try{out.bodyLen=String((d.body&&d.body.innerText)||"").length;}catch(_b){}try{out.aLen=d.querySelectorAll?d.querySelectorAll("a[href]").length:0;}catch(_a){}try{var F=d.querySelectorAll("iframe,frame"),sig=[],i;for(i=0;i<F.length&&i<36;i++){sig.push(String(F[i].getAttribute("src")||"").substring(0,96));}out.iframeN=F.length;out.iframeSrcSig=sig.join("|");}catch(_f){}return out;}catch(e){return{path:"",hash:"",title:"",iframeN:0,iframeSrcSig:"",bodyLen:0,aLen:0};}}'
        . 'function ipmiProxyIloCapturePreLaunchSnapshot(){try{return ipmiProxyIloCaptureLaunchSnapshotDoc(document);}catch(e){return{path:"",hash:"",title:"",iframeN:0,iframeSrcSig:"",bodyLen:0,aLen:0};}}'
        . 'function ipmiProxyIloCapturePostLaunchSnapshot(){return ipmiProxyIloCapturePreLaunchSnapshot();}'
        . 'function ipmiProxyIloDiffLaunchSnapshots(a,b){try{a=a||{};b=b||{};var ch=[],meaning=false;if(String(a.path||"")!==String(b.path||"")){ch.push("path");meaning=true;}if(String(a.hash||"")!==String(b.hash||"")){ch.push("hash");meaning=true;}if((a.iframeN|0)!==(b.iframeN|0)){ch.push("iframe_count");meaning=true;}if(String(a.iframeSrcSig||"")!==String(b.iframeSrcSig||"")){ch.push("iframe_src");meaning=true;}if(Math.abs((a.bodyLen|0)-(b.bodyLen|0))>80){ch.push("body_text_len");meaning=true;}if((a.aLen|0)!==(b.aLen|0)){ch.push("anchor_count");meaning=true;}return{changed:ch,meaningful:meaning};}catch(e){return{changed:[],meaningful:false};}}'
        . 'function ipmiProxyIloLaunchFunctionContextFingerprint(){try{var s=ipmiProxyIloCapturePreLaunchSnapshot();return String(s.path||"")+"#"+String(s.hash||"")+":"+String(s.iframeN||0)+":"+String(s.iframeSrcSig||"").substring(0,200);}catch(e){return"";}}'
        . 'function ipmiProxyIloRecordLaunchFunctionFound(st,src,ctxIdx){try{if(st)st.launchFunctionFound=true;try{_kvmDbg("ilo_launch_function_found",{src:String(src||""),ctx:ctxIdx});}catch(_x){}}catch(e){}}'
        . 'function ipmiProxyIloLaunchFunctionPreconditions(w,il){try{var o={iLO_present:!!il,startHtml5Irc_type:typeof(il&&il.startHtml5Irc),argLength:-1,hasAppFrame:false,appFrameSrc:""};try{if(il&&il.startHtml5Irc)o.argLength=il.startHtml5Irc.length;}catch(_l){}try{if(w&&w.document&&w.document.getElementById){var af=w.document.getElementById("appFrame");if(af){o.hasAppFrame=true;o.appFrameSrc=String(af.getAttribute("src")||"").substring(0,120);}}}catch(_a){}try{_kvmDbg("ilo_launch_function_context_checked",o);}catch(_c){}var inc=!o.hasAppFrame||!o.appFrameSrc||o.appFrameSrc.toLowerCase().indexOf("application")<0;if(inc&&o.startHtml5Irc_type==="function"){try{_kvmDbg("ilo_launch_function_present_but_context_incomplete",{reason:"appframe_not_application",appFrameSrc:o.appFrameSrc});}catch(_p){}}return o;}catch(e){return{iLO_present:false};}}'
        . 'function ipmiProxyIloCanInvokeLaunchFunction(st){try{if(!st)return true;if(st.shellLaunchProbeExhausted)return false;if((st.launchFnBudgetSpent|0)>=(st.launchFnBudgetMax|0))return false;if(st.shellLaunchNoEffectLocked&&!st.launchFnContextChanged)return false;return true;}catch(e){return true;}}'
        . 'function ipmiProxyIloRecordLaunchFunctionBudgetSpend(st,label){try{if(!st)return;st.launchFnBudgetSpent=(st.launchFnBudgetSpent|0)+1;try{_kvmDbg("ilo_launch_function_budget_spent",{spent:st.launchFnBudgetSpent,max:st.launchFnBudgetMax||2,label:String(label||"")});}catch(_b){}if((st.launchFnBudgetSpent|0)>=(st.launchFnBudgetMax|0)){try{_kvmDbg("ilo_launch_function_budget_exhausted",{spent:st.launchFnBudgetSpent});}catch(_e){}st.shellLaunchProbeExhausted=true;}}catch(e){}}'
        . 'function ipmiProxyIloShouldRetryLaunchFunction(st){try{if(!st)return false;if(!st.shellLaunchNoEffectLocked)return ipmiProxyIloCanInvokeLaunchFunction(st);return !!st.launchFnContextChanged;}catch(e){return false;}}'
        . 'function ipmiProxyIloInvokeILOStartHtml5Once(il,w,gi,st){try{var pre=ipmiProxyIloCapturePreLaunchSnapshot();try{_kvmDbg("ilo_launch_pre_snapshot",pre);}catch(_ps){}try{_kvmDbg("ilo_launch_function_invocation_attempted",{fn:"iLO.startHtml5Irc",ctx:gi});}catch(_ia){}var threw=false,retOk=false;try{if(il&&typeof il.startHtml5Irc==="function"){il.startHtml5Irc.call(il,{mode:"WINDOW"});retOk=true;}}catch(e1){threw=true;try{if(il&&typeof il.startHtml5Irc==="function"){il.startHtml5Irc.call(il);retOk=true;threw=false;}}catch(e2){threw=true;}}try{_kvmDbg("ilo_launch_function_invocation_returned",{ctx:gi,threw:threw?1:0});}catch(_ir){}if(threw){try{_kvmDbg("ilo_launch_function_invocation_failed",{fn:"iLO.startHtml5Irc",ctx:gi});}catch(_if){}return"threw";}var post=ipmiProxyIloCapturePostLaunchSnapshot();try{_kvmDbg("ilo_launch_post_snapshot",post);}catch(_po){}var df=ipmiProxyIloDiffLaunchSnapshots(pre,post);try{_kvmDbg("ilo_launch_snapshot_diff",{changed:df.changed.join(","),meaningful:df.meaningful?1:0});}catch(_sd){}if(df.meaningful){try{_kvmDbg("ilo_launch_function_effective",{fn:"iLO.startHtml5Irc",via:"state_change"});if(df.changed.indexOf("path")>=0)_kvmDbg("ilo_launch_action_changed_url",{});if(df.changed.indexOf("iframe_src")>=0||df.changed.indexOf("iframe_count")>=0)_kvmDbg("ilo_launch_action_changed_frame_state",{});}catch(_ef){}st.launchFunctionEffective=true;return"ilo_startHtml5Irc_effective";}try{_kvmDbg("ilo_launch_function_no_effect",{fn:"iLO.startHtml5Irc",ctx:gi});try{_kvmDbg("ilo_launch_action_no_effect",{phase:"immediate_diff",ctx:gi});}catch(_ne){}}catch(_nf){}st.launchFunctionNoEffectObserved=true;try{st.shellLaunchProvenIneffective=true;}catch(_spi){}return"ilo_startHtml5Irc_no_effect";}catch(e){try{_kvmDbg("ilo_launch_function_invocation_failed",{fn:"iLO.startHtml5Irc",err:String(e)});}catch(_e2){}return"threw";}}'
        . 'function ipmiProxyIloTryNamedFn(w,fn,ctxIdx,label,st){try{if(st&&!ipmiProxyIloCanInvokeLaunchFunction(st))return"";if(!w||typeof w[fn]!=="function")return"";ipmiProxyIloRecordLaunchFunctionFound(st||{},label||fn,ctxIdx);try{_kvmDbg("ilo_launch_function_invocation_attempted",{fn:fn,ctx:ctxIdx});}catch(_ia){}var modes=[function(){w[fn].call(w,{mode:"WINDOW"});},function(){w[fn].call(w);},function(){w[fn]();}];for(var mi=0;mi<modes.length;mi++){try{modes[mi]();try{_kvmDbg("ilo_launch_function_invocation_succeeded",{fn:fn,ctx:ctxIdx});}catch(_is){}if(st)ipmiProxyIloRecordLaunchFunctionBudgetSpend(st,fn);return"fn_"+fn;}catch(_fx){}}try{_kvmDbg("ilo_launch_function_invocation_failed",{fn:fn,ctx:ctxIdx});}catch(_if){}if(st)ipmiProxyIloRecordLaunchFunctionBudgetSpend(st,fn);}catch(_e){}return"";}'
        . 'function tryProbeIloLaunchGlobals(ctxArr,st){try{var nm=["openHtml5Irc","launchHtml5Irc","openIntegratedRemoteConsole","openRemoteConsole","launchRemoteConsole","startIntegratedRemoteConsole","showRemoteConsole","openHtmlConsole","launchHtmlConsole","openIRC","startIRC","openVirtualConsole","launchVirtualConsole"];if(!st||st.shellLaunchProbeExhausted)return"";if(!ipmiProxyIloCanInvokeLaunchFunction(st))return"";for(var gi=0;gi<ctxArr.length;gi++){var w=ctxArr[gi];if(!w)continue;var il=null;try{il=w.iLO;}catch(_il0){il=null;}if(il&&typeof il.startHtml5Irc==="function"){ipmiProxyIloLaunchFunctionPreconditions(w,il);ipmiProxyIloRecordLaunchFunctionFound(st,"iLO.startHtml5Irc",gi);var inv=ipmiProxyIloInvokeILOStartHtml5Once(il,w,gi,st);ipmiProxyIloRecordLaunchFunctionBudgetSpend(st,"iLO.startHtml5Irc");if(inv&&inv.indexOf("effective")>=0)return inv;if(inv==="ilo_startHtml5Irc_no_effect"||inv==="threw")return"";}var r0=ipmiProxyIloTryNamedFn(w,"startHtml5Irc",gi,"global_startHtml5Irc",st);if(r0)return r0;if(il){for(var ni=0;ni<nm.length;ni++){var fn=nm[ni],hit="";try{if(typeof il[fn]==="function"){ipmiProxyIloRecordLaunchFunctionFound(st,"iLO."+fn,gi);try{_kvmDbg("ilo_launch_function_invocation_attempted",{fn:"iLO."+fn,ctx:gi});}catch(_ia2){}try{il[fn].call(il,{mode:"WINDOW"});hit="ilo_"+fn;}catch(_i0){try{il[fn].call(il);hit="ilo_"+fn;}catch(_i1){try{il[fn]();hit="ilo_"+fn;}catch(_i2){}}}}}catch(_i3){}if(hit){ipmiProxyIloRecordLaunchFunctionBudgetSpend(st,fn);return hit;}}}for(var gj=0;gj<nm.length;gj++){var r1=ipmiProxyIloTryNamedFn(w,nm[gj],gi,"global_"+nm[gj],st);if(r1)return r1;}}catch(gp){}return"";}'
        . 'function tryNavigateLauncherFrameOnce(doc,st){try{if(!doc||!st||st.frameNavDone)return false;var fc=ipmiProxyIloFindNavigableFrame(doc);if(!fc||!fc.el)return false;if(fc.score>=10&&fc.score<14)_kvmDbg("ilo_console_frame_candidate_rejected",{score:fc.score,kind:fc.kind||"",reason:"below_nav_threshold"});var el=fc.el,src=String(el.getAttribute("src")||"").toLowerCase(),fid=String(el.getAttribute("id")||"").toLowerCase(),fnm=String(el.getAttribute("name")||"").toLowerCase();if(src.indexOf("rc_info")>=0||src.indexOf("application")>=0)return false;var shellMain=(fc.kind==="shell_frame")&&(fid==="framecontent"||fnm==="framecontent"||src.indexOf("content.html")>=0||src===""||src==="about:blank");var consoleEmpty=(fc.kind==="console_frame_candidate")&&(src===""||src==="about:blank"||src.indexOf("content.html")>=0);if(shellMain&&fc.score>=14){st.frameNavDone=true;_kvmDbg("ilo_console_frame_candidate_followed",{action:"set_src_rc_info",score:fc.score,kind:fc.kind,reason:"shell_main_frame"});try{el.setAttribute("src","html/rc_info.html");return true;}catch(sn0){}}if(fc.kind==="shell_frame")return false;if(fc.score<32)return false;if(consoleEmpty){st.frameNavDone=true;_kvmDbg("ilo_console_frame_candidate_followed",{action:"set_src_rc_info",score:fc.score,kind:fc.kind,reason:"launcher_empty"});try{el.setAttribute("src","html/rc_info.html");return true;}catch(sn1){}}}catch(nf){}return false;}'
        . 'function ipmiProxyIloInspectSameOriginFrameForLaunch(fw){try{if(!fw||!fw.document)return null;var ifs=fw.document.querySelectorAll("iframe,frame");for(var ii=0;ii<ifs.length&&ii<28;ii++){try{var w=ifs[ii].contentWindow;if(!w||!w.document)continue;var el=findIloDeepLaunch({document:w.document})||findIloHeuristicLaunch({document:w.document})||findIloBestConsoleHrefClickable(w.document);if(el){_kvmDbg("ilo_frame_subdocument_launch_control",{iframe_index:ii});return el;}}catch(e2){}}}catch(e){}return null;}'
        . 'function ipmiProxyIloHrefConsoleScore(href){try{var h=String(href||"").toLowerCase();if(!h||h.indexOf("javascript:")===0||h.indexOf("#")===0)return-100;if(h.indexOf("logout")>=0||h.indexOf("log_out")>=0)return-80;var s=0;if(h.indexOf("rc_info")>=0)s+=70;if(h.indexOf("irc")>=0&&h.indexOf(".html")>=0)s+=55;if(h.indexOf("application.html")>=0)s+=50;if(h.indexOf("remote")>=0&&h.indexOf("console")>=0)s+=48;if(h.indexOf("html5")>=0)s+=40;if(h.indexOf("kvm")>=0)s+=35;if(h.indexOf("jnlp")>=0)s+=28;if(h.indexOf("java")>=0&&h.indexOf("irc")>=0)s+=22;if(h.indexOf("console")>=0)s+=18;if(h.indexOf("virtual")>=0&&h.indexOf("console")>=0)s+=20;return s;}catch(e){return 0;}}'
        . 'function findIloBestConsoleHrefClickable(doc){try{if(!doc||!doc.querySelectorAll)return null;var A=doc.querySelectorAll("a[href]"),best=null,bs=-999;for(var ai=0;ai<A.length&&ai<420;ai++){var a=A[ai],href=a.getAttribute("href")||"",sc=ipmiProxyIloHrefConsoleScore(href),tx=String(a.textContent||a.innerText||"");if(iloConsoleKeyword(tx))sc+=25;if(sc>bs){bs=sc;best=a;}}if(best&&bs>=12)return best;}catch(e){}return null;}'
        . 'function findIloDeepLaunchRecursive(ctx,depth){try{if(!ctx||!ctx.document||depth>4)return null;var d0=findIloDeepLaunch(ctx)||findIloHeuristicLaunch(ctx)||findIloBestConsoleHrefClickable(ctx.document);if(d0)return d0;var ifs=ctx.document.querySelectorAll("iframe,frame");for(var fi=0;fi<ifs.length&&fi<18;fi++){try{var w=ifs[fi].contentWindow;if(!w)continue;var hit=findIloDeepLaunchRecursive(w,depth+1);if(hit)return hit;}catch(fr){}}}catch(e2){}return null;}'
        . 'function tryFollowBoundedConsoleHref(ctxArr,st){try{if(!st)return false;var pl=pathLower();var onShell=(pl.indexOf("/index.html")>=0||pl.indexOf("/restgui/")>=0||pl==="/"||pl==="");if(!onShell&&!ipmiProxyIloPathIsManagementShellish())return false;var best=null,bDoc=null,bSc=-999;for(var ci=0;ci<ctxArr.length;ci++){var c=ctxArr[ci];if(!c||!c.document)continue;var a=findIloBestConsoleHrefClickable(c.document);if(!a)continue;var href=String(a.getAttribute("href")||""),sc=ipmiProxyIloHrefConsoleScore(href)+10;if(sc>bSc){bSc=sc;best=a;bDoc=c.document;}}if(!best||bSc<14)return false;_kvmDbg("ilo_launch_discovery_escalation_attempted",{kind:"bounded_console_href",score:bSc});_kvmDbg("ilo_launch_navigation_triggered",{target:String(best.getAttribute("href")||"").substring(0,120)});try{if(typeof best.click==="function"){best.click();return true;}}catch(_c0){}try{if(bDoc&&bDoc.createEvent){var ev=bDoc.createEvent("MouseEvents");ev.initEvent("click",true,true);best.dispatchEvent(ev);return true;}}catch(_c1){}}catch(_bf){}return false;}'
        . 'function tryShellDiscoveryEscalationOnce(ctxArr,st){try{if(!st||st.shellEscalationConsumed)return"";if(kvmIloWsTransportEvidence())return"";st.shellEscalationConsumed=true;try{_kvmDbg("ilo_launch_discovery_escalation_allowed",{reason:"shell_index_no_transport"});}catch(_ea){}if(tryFollowBoundedConsoleHref(ctxArr,st)){st.discNavTriggered=true;st.anyLaunchAction=true;st.discoveryEscalationKind="console_href";try{st.appNavPendingSince=kvmNow();}catch(_an0){}try{_kvmDbg("ilo_launch_discovery_escalation_attempted",{kind:"console_href_ok"});}catch(_ok){}return"href";}try{if(st&&st.shellLaunchProvenIneffective){try{_kvmDbg("ilo_shell_launch_proven_ineffective",{note:"authoritative_spa_escalation"});}catch(_s1){}}try{_kvmDbg("ilo_application_path_promotion_allowed",{target:"html/application.html"});}catch(_ap0){}try{if(st){st.applicationPathPromotionActive=true;st.shellPathAbandoned=true;}try{_kvmDbg("ilo_shell_path_abandoned_for_application",{});}catch(_sp){}}catch(_ap1){}try{_kvmDbg("ilo_launch_discovery_escalation_attempted",{kind:"spa_bootstrap_fallback",target:"html/application.html"});}catch(_e0){}try{if(st){st.appNavPendingSince=kvmNow();st.appNavCommitted=false;}}catch(_an1){}try{_kvmDbg("ilo_application_path_promotion_triggered",{});}catch(_pt){}go("/html/application.html?ipmi_kvm_auto=1");st.discNavTriggered=true;st.anyLaunchAction=true;st.discoveryEscalationKind="spa_bootstrap";try{_kvmDbg("ilo_application_navigation_triggered",{target:"html/application.html"});}catch(_nt){}markAppRedirected();return"spa";}catch(_ge){try{_kvmDbg("ilo_launch_discovery_escalation_failed",{err:String(_ge)});}catch(_ef){}}return"";}catch(_se){return"";}}'
        . 'function findIloDeepLaunch(ctx){try{var d=ctx.document;if(!d||!d.querySelectorAll)return null;var L=d.querySelectorAll("a[href],button,[role=button],[role=menuitem],input[type=button],input[type=submit],label,.btn,.hpJump,.menuItem,.nav-item,a[class*=nav],a[class*=menu],[data-action],[data-url],[data-href],[data-target],.tree_view a,.gwt-Anchor,td[onclick],div[onclick],span[onclick],li[onclick]");for(var i=0;i<L.length&&i<520;i++){var e=L[i],t=String(e.textContent||e.innerText||""),h=String(e.getAttribute("href")||"").toLowerCase(),oc=String(e.getAttribute("onclick")||"").toLowerCase(),da=String(e.getAttribute("data-action")||"").toLowerCase(),du=String(e.getAttribute("data-url")||"").toLowerCase(),dh=String(e.getAttribute("data-href")||"").toLowerCase(),dt=String(e.getAttribute("data-target")||"").toLowerCase(),ti=String(e.getAttribute("title")||"").toLowerCase(),ar=String(e.getAttribute("aria-label")||"").toLowerCase();if(iloConsoleKeyword(t)||iloConsoleKeyword(h)||iloConsoleKeyword(oc)||iloConsoleKeyword(da)||iloConsoleKeyword(du)||iloConsoleKeyword(dh)||iloConsoleKeyword(dt)||iloConsoleKeyword(ti)||iloConsoleKeyword(ar)||h.indexOf("rc_info")>=0||h.indexOf("application.html")>=0||h.indexOf("irc")>=0||h.indexOf("jnlp")>=0||h.indexOf("html5")>=0||h.indexOf("remote-console")>=0||h.indexOf("remote_console")>=0||h.indexOf("kvm")>=0&&h.indexOf("console")>=0)return e;}}catch(e2){}return null;}'
        . 'function findIloHeuristicLaunch(ctx){try{var d=ctx.document;if(!d||!d.querySelectorAll)return null;var L=d.querySelectorAll("a[href],button,[role=button],input[type=button],input[type=submit],label,.btn");for(var i=0;i<L.length&&i<140;i++){var e=L[i],t=String(e.textContent||""),h=String(e.getAttribute("href")||"").toLowerCase(),oc=String(e.getAttribute("onclick")||"").toLowerCase(),dt=String(e.getAttribute("data-localize")||"").toLowerCase();if(iloKvText(t)||iloKvText(h)||iloConsoleKeyword(t)||iloConsoleKeyword(h)||iloKvText(oc)||iloKvText(dt)||h.indexOf("irc")>=0||h.indexOf("html5")>=0||h.indexOf("remote")>=0&&h.indexOf("console")>=0){return e;}}}catch(e2){}return null;}'
        . 'function wireIloAppFrame(ctx){try{'
        . 'if(!ctx)return;'
        . 'var host=bindIloTopPage(ctx)||ctx;'
        . 'if(host&&host.iLOGlobal&&host.iLOGlobal.topPage){host.iLOGlobal.topPage.appFrame=host;}'
        . '}catch(e){}}'
        . 'function ensureIloRcPageLoaded(ctx){try{'
        . 'var host=getIloShellHost(ctx);'
        . 'if(!host||ctx!==host)return false;'
        . 'var fc=getIloFrameContent(host);'
        . 'if(!fc||typeof fc.loadContent!=="function")return false;'
        . 'if(hasIloRcPage(host))return false;'
        . 'var pendingTs=0;'
        . 'try{pendingTs=Number(host.__ipmi_rc_info_loading_ts||0);}catch(_e2pre){pendingTs=0;}'
        . 'if(pendingTs>0&&(Date.now()-pendingTs)<15000){return false;}'
        . 'var iframeEl=getIloIframeContentEl(host);'
        . 'if(iframeEl&&!iframeEl.__ipmi_rc_load_bound){try{iframeEl.addEventListener("load",function(){try{host.__ipmi_rc_info_loading_ts=0;}catch(_eL){}},true);iframeEl.__ipmi_rc_load_bound=true;}catch(_eLb){}}'
        . 'var iframeSrc="";'
        . 'try{iframeSrc=String((iframeEl&&iframeEl.getAttribute&&iframeEl.getAttribute("src"))||"").toLowerCase();}catch(_e2a){}'
        . 'if(iframeSrc.indexOf("rc_info.html")!==-1){'
        . 'try{'
        . 'if(pendingTs<=0){host.__ipmi_rc_info_loading_ts=Date.now();return false;}'
        . 'if((Date.now()-pendingTs)<15000){return false;}'
        . '}catch(_e2b){return false;}'
        . '}'
        . 'try{if(host.iLOGlobal){host.iLOGlobal.initialLink="rc_info.html";host.iLOGlobal.content="rc_info.html";host.iLOGlobal.initialTab=0;}}catch(_e3){}'
        . 'try{if(fc.iLOGlobal){fc.iLOGlobal.initialLink="rc_info.html";fc.iLOGlobal.initialTab=0;}}catch(_e3b){}'
        . 'try{_kvmDbg("ilo_rc_info_navigation","loadContent");host.__ipmi_rc_info_loading_ts=Date.now();fc.loadContent("rc_info.html");return true;}catch(_e4){}'
        . 'return false;'
        . '}catch(e){return false;}}'
        . 'function ensureIloGlobalStartPatched(ctx){try{'
        . 'if(!ctx||typeof ctx.startHtml5Irc!=="function"||ctx.__ipmi_global_start_patched||!isWrapperStartFn(ctx.startHtml5Irc)){return;}'
        . 'var orig=ctx.startHtml5Irc;'
        . 'ctx.startHtml5Irc=function(){'
        . 'var started=false,cc=collectContexts();'
        . 'for(var i=0;i<cc.length;i++){if(callStart(cc[i])||callIloStart(cc[i])){started=true;break;}}'
        . 'if(started){return false;}'
        . 'try{return orig.apply(this,arguments);}catch(e){return false;}'
        . '};'
        . 'ctx.__ipmi_global_start_patched=true;'
        . '}catch(e){}}'
        . 'function ensureIloRcButtonPatched(ctx){try{'
        . 'var btn=findIloHtml5Button(ctx);'
        . 'if(!btn||btn.__ipmi_kvm_bound)return;'
        . 'btn.__ipmi_kvm_bound=true;'
        . 'try{btn.setAttribute("data-ipmi-kvm-ready","1");}catch(_e0){}'
        . '}catch(e){}}'
        . 'function callIloStart(ctx){'
        . 'if(!ctx)return false;'
        . 'var host=bindIloTopPage(ctx)||findIloRendererHost(ctx)||ctx;'
        . 'ensureIloStartPatched(ctx);'
        . 'if(host&&host!==ctx){ensureIloStartPatched(host);}'
        . 'clearIloStaleRenderer(host);clearIloStaleRenderer(ctx);'
        . 'wireIloAppFrame(host||ctx);'
        . 'var fired=false;'
        . 'try{if(host&&host.iLO&&typeof host.iLO.startHtml5Irc==="function"){host.iLO.startHtml5Irc();fired=true;}}catch(e0){}'
        . 'try{if(!fired&&ctx.iLO&&typeof ctx.iLO.startHtml5Irc==="function"){ctx.iLO.startHtml5Irc();fired=true;}}catch(e1){}'
        . 'if(!fired)return false;'
        . 'return consoleVisible(host)||consoleVisible(ctx);}'
        . 'function callStart(ctx){'
        . 'if(!ctx)return false;'
        . 'var directTop=getIloDirectTopRenderer(ctx);'
        . 'if(directTop){ensureIloFrameResizeShim(directTop);clearIloStaleRenderer(directTop);try{directTop.startHtml5Irc({mode:"WINDOW"});}catch(_dt1){}try{if(!consoleVisible(directTop)){directTop.startHtml5Irc();}}catch(_dt2){}if(consoleVisible(directTop))return true;}'
        . 'var host=findIloRendererHost(ctx)||bindIloTopPage(ctx)||ctx;'
        . 'ensureIloFrameResizeShim(host);clearIloStaleRenderer(host);clearIloStaleRenderer(ctx);'
        . 'if(host&&isRendererStartFn(host.startHtml5Irc)){'
        . 'try{host.startHtml5Irc({mode:"WINDOW"});}catch(e1){}'
        . 'try{if(!consoleVisible(host)&&!consoleVisible(ctx)){host.startHtml5Irc();}}catch(e2){}'
        . 'if(consoleVisible(host)||consoleVisible(ctx))return true;'
        . '}'
        . 'return false;}'
        . 'function clickHtml5Anchor(ctx,skipButton){try{'
        . 'if(!ctx||!ctx.document||!ctx.document.querySelector)return false;'
        . 'var btn=findIloHtml5Button(ctx);'
        . 'if(!skipButton&&btn){if(typeof btn.click==="function"){btn.click();return true;}'
        . 'if(ctx.document.createEvent){var bev=ctx.document.createEvent("MouseEvents");bev.initEvent("click",true,true);btn.dispatchEvent(bev);return true;}}'
        . 'var a=ctx.document.querySelector("#html5_irc_label a");'
        . 'if(!a){var heur=findIloHeuristicLaunch(ctx);if(heur){_kvmDbg("ilo_click_candidate_found","heuristic");if(typeof heur.click==="function"){heur.click();return true;}if(ctx.document.createEvent){var evh=ctx.document.createEvent("MouseEvents");evh.initEvent("click",true,true);heur.dispatchEvent(evh);return true;}}return false;}'
        . 'if(typeof a.click==="function"){a.click();return true;}'
        . 'if(ctx.document.createEvent){var ev=ctx.document.createEvent("MouseEvents");ev.initEvent("click",true,true);a.dispatchEvent(ev);return true;}'
        . '}catch(e){}return false;}'
        . 'function tryExpandIloHiddenMenus(doc,tag){try{if(!doc||!doc.querySelectorAll)return false;var M=doc.querySelectorAll(".menu-toggle,.nav-toggle,.gwt-MenuBar,.hp-menu-button,.hp-menu,.nav-item button,[class*=expand]");for(var i=0;i<M.length&&i<16;i++){var e=M[i];try{if(e&&e.offsetParent!==null){if(typeof e.click==="function"){e.click();return true;}}}catch(_me){}}}catch(e){}return false;}'
        . 'function tryClickIloDiscoveryLaunch(ctxArr,tag,st){try{var gp="";if(!st||!st.shellLaunchProbeExhausted){gp=tryProbeIloLaunchGlobals(ctxArr,st);}else{try{_kvmDbg("ilo_launch_function_retry_denied",{reason:"budget_exhausted"});}catch(_rd0){}}if(gp)return gp;for(var qi=0;qi<ctxArr.length;qi++){var c=ctxArr[qi];if(!c||!c.document)continue;if(st&&tryNavigateLauncherFrameOnce(c.document,st))return"frame_nav_rc_info";var dl=findIloDeepLaunch(c)||findIloDeepLaunchRecursive(c,0);if(!dl){var ah=findIloBestConsoleHrefClickable(c.document);if(ah){_kvmDbg("ilo_launch_control_found",{src:"console_href",tag:tag||""});dl=ah;}}if(dl){_kvmDbg("ilo_launch_control_found",{src:"deep_scan",tag:tag||""});if(typeof dl.click==="function"){dl.click();return"deep";}if(c.document.createEvent){var ev=c.document.createEvent("MouseEvents");ev.initEvent("click",true,true);dl.dispatchEvent(ev);return"deep";}}var ins=ipmiProxyIloInspectSameOriginFrameForLaunch(c);if(ins){_kvmDbg("ilo_frame_contains_launch_surface",{tag:tag||""});if(typeof ins.click==="function"){ins.click();return"frame_inspect";}if(c.document&&c.document.createEvent){var ev2=c.document.createEvent("MouseEvents");ev2.initEvent("click",true,true);ins.dispatchEvent(ev2);return"frame_inspect";}}var fc=ipmiProxyIloFindConsoleFrameCandidate(c.document);if(fc&&fc.el){_kvmDbg("ilo_launch_frame_candidate_found",{score:fc.score,kind:fc.kind||"",tag:tag||""});if(fc.score>=24){_kvmDbg("ilo_console_frame_candidate_detected",{score:fc.score,kind:fc.kind||"",tag:tag||""});try{if(fc.el.focus)fc.el.focus();}catch(_fe){}}else if(fc.score>=10){_kvmDbg("ilo_console_frame_candidate_rejected",{score:fc.score,kind:fc.kind||"",reason:"below_action_threshold"});}}}}catch(_q){}return"";}'
        . 'function collectContexts(){'
        . 'var out=[];'
        . 'function add(c){if(!c)return;for(var i=0;i<out.length;i++){if(out[i]===c)return;}out.push(c);}'
        . 'try{add(window);}catch(e0){}'
        . 'try{if(window.parent&&window.parent!==window)add(window.parent);}catch(e1){}'
        . 'try{if(window.parent&&window.parent.parent&&window.parent.parent!==window.parent)add(window.parent.parent);}catch(e1b){}'
        . 'try{if(window.top&&window.top!==window)add(window.top);}catch(e2){}'
        . 'try{if(window.top&&window.top.frames&&window.top.frames.appFrame)add(window.top.frames.appFrame);}catch(e2b){}'
        . 'try{if(window.frames&&window.frames.frameContent)add(window.frames.frameContent);}catch(e3){}'
        . 'try{if(window.frames&&window.frames.frameContent&&window.frames.frameContent.frames&&window.frames.frameContent.frames.iframeContent){add(window.frames.frameContent.frames.iframeContent);}}catch(e4){}'
        . 'try{if(window.parent&&window.parent.frames&&window.parent.frames.frameContent)add(window.parent.frames.frameContent);}catch(e5){}'
        . 'try{if(window.parent&&window.parent.frames&&window.parent.frames.frameContent&&window.parent.frames.frameContent.frames&&window.parent.frames.frameContent.frames.iframeContent){add(window.parent.frames.frameContent.frames.iframeContent);}}catch(e6){}'
        . 'try{if(window.frames){for(var fi=0;fi<window.frames.length&&fi<36;fi++){try{add(window.frames[fi]);}catch(fx){}}}}catch(f0){}'
        . 'try{if(window.top&&window.top.frames){for(var fi2=0;fi2<window.top.frames.length&&fi2<36;fi2++){try{add(window.top.frames[fi2]);}catch(fx2){}}}}catch(f1){}'
        . 'return out;}';
}
